#!/bin/bash


set -o errexit
set -o pipefail
set -o nounset

python manage.py makemigrations
# --run-syncdb - Used here because tests were failing, when starting new database.
python manage.py migrate --run-syncdb
python manage.py runserver 0.0.0.0:8000