# Generated by Django 4.1.3 on 2022-12-11 11:18

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_scrape", models.DateTimeField(auto_now_add=True)),
                ("product_name", models.CharField(max_length=255)),
                ("product_description", models.TextField(blank=True)),
                (
                    "product_traits",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "product_price_for_unit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("product_unit_type", models.CharField(blank=True, max_length=50)),
                ("product_brand", models.CharField(blank=True, max_length=255)),
                ("product_web_id", models.CharField(blank=True, max_length=255)),
                ("product_sku", models.CharField(blank=True, max_length=255)),
                ("product_ean", models.CharField(blank=True, max_length=13)),
                ("product_is_in_promo", models.BooleanField(default=False)),
                ("product_promo_type", models.CharField(blank=True, max_length=255)),
                ("product_warranty_time", models.CharField(blank=True, max_length=100)),
                ("product_availability", models.BooleanField(default=False)),
                ("product_current_stock", models.CharField(blank=True, max_length=255)),
                (
                    "parrent_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.productdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=200, unique=True)),
                ("module_name", models.CharField(max_length=100)),
                ("scraper_class", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discovery_url", models.CharField(max_length=255, unique=True)),
                ("current_url", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("canonical_url", models.CharField(blank=True, max_length=255)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_discovery", models.DateTimeField(blank=True, null=True)),
                ("last_scrape", models.DateTimeField(blank=True, null=True)),
                (
                    "parrent_categories_pages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(blank=True, null=True),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "parrent_website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.website",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductDataExtraField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("value", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "parrent_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.productdata",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ProductExtraField",
            },
        ),
        migrations.AddField(
            model_name="productdata",
            name="product_parrent_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.productpage"
            ),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discovery_url", models.CharField(max_length=255, unique=True)),
                ("current_url", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("canonical_url", models.CharField(blank=True, max_length=255)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_discovery", models.DateTimeField(blank=True, null=True)),
                ("last_scrape", models.DateTimeField(blank=True, null=True)),
                ("main_title", models.CharField(max_length=100)),
                ("main_description", models.TextField()),
                (
                    "parrent_website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.website",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discovery_url", models.CharField(max_length=255, unique=True)),
                ("current_url", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("canonical_url", models.CharField(blank=True, max_length=255)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_discovery", models.DateTimeField(blank=True, null=True)),
                ("last_scrape", models.DateTimeField(blank=True, null=True)),
                ("company_name", models.CharField(max_length=255, unique=True)),
                ("company_address", models.TextField(blank=True)),
                ("company_phone", models.CharField(blank=True, max_length=255)),
                (
                    "company_email_address",
                    models.EmailField(blank=True, max_length=254),
                ),
                (
                    "parrent_website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.website",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CategoryPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discovery_url", models.CharField(max_length=255, unique=True)),
                ("current_url", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("canonical_url", models.CharField(blank=True, max_length=255)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_discovery", models.DateTimeField(blank=True, null=True)),
                ("last_scrape", models.DateTimeField(blank=True, null=True)),
                ("category_name", models.CharField(max_length=255)),
                (
                    "category_nesting_level",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "First"),
                            (2, "Second"),
                            (3, "Third"),
                            (4, "Fourth"),
                            (5, "Fifth"),
                            (6, "Sixth"),
                        ],
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                ("category_description", models.TextField(blank=True)),
                (
                    "related_categories_last_discovery",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "related_products_last_discovery",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "parrent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.categorypage",
                    ),
                ),
                (
                    "parrent_website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.website",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(blank=True, to="projects.productpage"),
                ),
            ],
            options={
                "verbose_name_plural": "CategoryPages",
            },
        ),
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discovery_url", models.CharField(max_length=255, unique=True)),
                ("current_url", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("canonical_url", models.CharField(blank=True, max_length=255)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_discovery", models.DateTimeField(blank=True, null=True)),
                ("last_scrape", models.DateTimeField(blank=True, null=True)),
                ("main_title", models.CharField(blank=True, max_length=100)),
                ("main_description", models.TextField(blank=True)),
                (
                    "parrent_website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.website",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discovery_url", models.CharField(max_length=255, unique=True)),
                ("current_url", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=False)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("canonical_url", models.CharField(blank=True, max_length=255)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_discovery", models.DateTimeField(blank=True, null=True)),
                ("last_scrape", models.DateTimeField(blank=True, null=True)),
                ("main_title", models.CharField(max_length=100)),
                ("main_description", models.TextField()),
                (
                    "parrent_website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.website",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
