# Generated by Django 4.1.3 on 2022-12-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="is_monitored",
            field=models.BooleanField(default=False),
        ),
    ]
