# Generated by Django 4.1.3 on 2022-12-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_website_is_monitored"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="module_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
