# Generated by Django 4.1 on 2022-08-24 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_url", models.CharField(max_length=255, unique=True)),
                ("category_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField()),
                ("category_description", models.TextField(blank=True)),
                ("meta_description", models.TextField(blank=True)),
                ("canonical_url", models.CharField(blank=True, max_length=255)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                (
                    "parrent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
    ]
