# Generated by Django 4.1 on 2022-09-04 21:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discovery_url", models.CharField(max_length=255, unique=True)),
                ("category_name", models.CharField(max_length=255)),
                ("current_url", models.CharField(blank=True, max_length=255)),
                (
                    "category_nesting_level",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "First"),
                            (2, "Second"),
                            (3, "Third"),
                            (4, "Fourth"),
                            (5, "Fifth"),
                            (6, "Sixth"),
                        ],
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(blank=True, null=True)),
                ("category_description", models.TextField(blank=True)),
                ("meta_description", models.TextField(blank=True)),
                ("canonical_url", models.CharField(blank=True, max_length=255)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_discovery", models.DateTimeField(blank=True, null=True)),
                ("last_scrape", models.DateTimeField(blank=True, null=True)),
                (
                    "related_categories_last_discovery",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "related_products_last_discovery",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "parrent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="categories.category",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, null=True, to="products.product"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
    ]
