# Generated by Django 4.1 on 2022-09-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="products",
            field=models.ManyToManyField(blank=True, to="products.product"),
        ),
    ]
