# Generated by Django 4.1 on 2022-08-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_root",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
