# Generated by Django 4.1 on 2022-08-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_category_is_root_alter_category_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_root",
            field=models.BooleanField(default=True),
        ),
    ]
