# Generated by Django 4.1 on 2022-08-24 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_alter_category_is_root"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="is_root",
        ),
        migrations.AddField(
            model_name="category",
            name="category_nesting_level",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "First"),
                    (2, "Second"),
                    (3, "Third"),
                    (4, "Fourth"),
                    (5, "Fifth"),
                    (6, "Sixth"),
                    (7, "Seventh"),
                    (8, "Eighth"),
                    (9, "Ninth"),
                    (10, "Tenth"),
                ],
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
