# Generated by Django 4.1 on 2022-08-22 14:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_url", models.CharField(max_length=255, unique=True)),
                ("product_name", models.CharField(max_length=255)),
                ("product_brand", models.CharField(blank=True, max_length=255)),
                (
                    "product_sku",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                ("product_description", models.TextField()),
                (
                    "product_traits",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        size=None,
                    ),
                ),
                ("product_promo_type", models.CharField(blank=True, max_length=255)),
                (
                    "product_price_for_unit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("product_unit_type", models.CharField(blank=True, max_length=50)),
                (
                    "product_price_for_piece",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("product_piece_type", models.CharField(blank=True, max_length=50)),
                (
                    "product_price_before_promo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("product_warranty_time", models.CharField(blank=True, max_length=100)),
                ("product_ean", models.CharField(blank=True, max_length=13)),
                ("product_availability", models.CharField(blank=True, max_length=50)),
                (
                    "product_current_stock",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
    ]
