# Generated by Django 4.1 on 2022-09-04 21:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discovery_url", models.CharField(max_length=255, unique=True)),
                ("product_name", models.CharField(max_length=255)),
                ("current_url", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(blank=True, null=True)),
                ("product_brand", models.CharField(blank=True, max_length=255)),
                ("product_sku", models.CharField(blank=True, max_length=255)),
                ("product_description", models.TextField(blank=True)),
                ("meta_description", models.TextField(blank=True)),
                ("canonical_url", models.CharField(blank=True, max_length=255)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                (
                    "product_traits",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("product_promo_type", models.CharField(blank=True, max_length=255)),
                ("product_warranty_time", models.CharField(blank=True, max_length=100)),
                ("product_ean", models.CharField(blank=True, max_length=13)),
                (
                    "parrent_categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(blank=True, null=True),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_discovery", models.DateTimeField(blank=True, null=True)),
                ("last_scrape", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductLocalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_tracked", models.BooleanField(default=False)),
                ("store_name", models.CharField(blank=True, max_length=255)),
                (
                    "product_price_for_unit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("product_unit_type", models.CharField(blank=True, max_length=50)),
                (
                    "product_price_for_piece",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("product_piece_type", models.CharField(blank=True, max_length=50)),
                (
                    "product_price_before_promo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("product_availability", models.CharField(blank=True, max_length=50)),
                (
                    "product_current_stock",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_scrape", models.DateTimeField(blank=True, null=True)),
                (
                    "parrent_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ProductLocalData",
            },
        ),
        migrations.CreateModel(
            name="ProductExtraField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("value", models.TextField(blank=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "parrent_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ProductExtraField",
            },
        ),
    ]
